### ISSUE TITLE
remove "dot" in announcements section

### ISSUE THREAD

**Issue by raghavg27** [raghavg27/csi-srmncr-website#4]
![image](https://user-images.githubusercontent.com/32697634/95037833-facfc880-06e9-11eb-9880-3251aa99ba6a.png)

**Comment by rocket8555** [comment]
Sir that's not a dot, it's a bullet point. If you want I can remove it but it will look nice when we write the announcement in bullet points.

**Comment by sarthak290** [comment]
Sir that not a dot , it's a bullet point. If you want I can remove it but I think I will look nice if we write announcement in bullet points.

**Comment by raghavg27** [comment]
add the bullets near to the text, that huge gap is looking weird.

**Comment by sarthak290** [comment]
Okay will resolve this soon. If their is still some problem with bullets I will use numbers instead of bullets.
